# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional, MCP uses stdio typically)

# Define environment variable defaults
ENV ES_HOST=""
ENV ES_API_KEY=""
ENV ES_USERNAME=""
ENV ES_PASSWORD=""
ENV ES_CA_CERT=""

# Start the MCP server
CMD [ "node", "dist/index.js" ]
